### ISSUE TITLE
Dupplication de code dans les vues pour lister les apparts

### ISSUE THREAD

**Issue by Em-AK** [WildCodeSchool/laloupe-0915-pillow#13]
Les vues `apparts/index.html.erb`,  `apparts/byprice.html.erb`, et  `apparts/byaccomodates.html.erb` sont un exemple flagrant de code dupliqué qui pourrais être factorisé.

Une première étape de refactoring peut se concentrer sur les vues en faisant appel à la même vue pour les 3 actions dans le controlleur avec un `render :index` en fin d'action.

Une deuxième étape serais de fusionner les trois actions `index`, `byprice` et `byaccomodates` en une seule action `index` dans le controlleur tout en gardant le comportement actuel coté utilisateur.

**Comment by Ava78** [comment]
Merci Emilien pour tes remontées.

**Comment by vgty** [comment]
thks !
